development:
  adapter: postgresql
  database: dev-website
  username: postgres
  password:

test:
  adapter: postgresql
  database: test-website
  username: postgres
  password:

production:
  adapter: postgresql
  database: website
  username: postgres
  password:
